# Generated by Django 4.2.20 on 2025-09-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tech',
            field=models.JSONField(null=True),
        ),
    ]
